name: SA Public Scripts CI

on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.16]

    steps:
      - uses: actions/checkout@v1

      - name: Prettier Action on PR
        if: github.event_name == 'pull_request'
        uses: creyD/prettier_action@v1.0
        with:
          prettier_options: "--write {**/*,*}.{js,hbs,html,json,md,yml,css,scss} !.github/workflows/**/* !dist/**/*"
          commit_message: "Run prettier via GitHub Action"
          branch: ${{ github.head_ref }}
          file_pattern: "."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Prettier Action on master
        if: github.ref == 'refs/heads/master'
        uses: creyD/prettier_action@v1.0
        with:
          prettier_options: "--write {**/*,*}.{js,html,json,md,yml,css,scss} !.github/workflows/**/* !dist/**/*"
          commit_message: "Run prettier via GitHub Action"
          branch: master
          file_pattern: "."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Run npm ci
        run: npm ci

      - name: Run npm test with BrowserStack Local
        uses: ianwalter/bsl@2.1.1
        with:
          args: sudo node ./test/index.js
        env:
          CI: true
          NODE_ENV: test
          DEBUG: false
          LOCATION: ${{ secrets.LOCATION }}
          BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}
          BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
